### ISSUE TITLE
JS error when you blow yourself up.

### ISSUE THREAD

**Issue by flukeout** [flukeout/snek#10]
![image](https://cloud.githubusercontent.com/assets/25212/18734243/590694b8-8027-11e6-8c98-0f6d9cc31f76.png)

STR
- Start a single player game
- After spawn dont move
- Drop a bomb
- You die and error happens...

cc @Pomax related to today's bombwork?

**Comment by Pomax** [comment]
I suspect "yes", will have to investigate tomorrow

**Comment by Pomax** [comment]
I can't reproduce this anymore on the latest code. If you can't either, let's close it.

**Comment by flukeout** [comment]
I cannot!
