### ISSUE TITLE
fellow game dev feedback

### ISSUE THREAD

**Issue by Pomax** [flukeout/snek#22]
```
<Pomax> multisnek.herokuapp.com
<Pomax> a friend and I are doing a session on simple multiplayer webgaming this mozfest
<Pomax> so we need a game - this is it
<Nightmare> Cool, but why so laggy? =(
<Nightmare> Is the movement not local?
<Nightmare> You are thrashing the heap too btw, You'd
<Nightmare> you're particles are dynamically resizing the array
<Nightmare> Use a circular buffer instead
<Nightmare> Constant size array, that will get rid of the GC hitching
<Nightmare> Really easy to setup and will keep things smooth. If you want to go a step further, store the minimum parts of the particle in a typed array [x,y,life] then have an object 'handle' the particles rather than storing fat objects in a standard array
<Nightmare> Chrome measures the particle update loop at 25ms on here, thats over a 60hz just to update them
```

**Comment by Pomax** [comment]
fixed size array cycling sounds pretty sensible.

**Comment by flukeout** [comment]
Cool, def want to hear more about the array thing, is that for the particles? Do they mean to use a giant  fixed-size array instead of adding and removing items all the time?

Yeah the lag. For sure it's there, we can take another stab at the client side prediction, but it's a big lift. Maybe when other things are stable?

**Comment by Pomax** [comment]
yeah, for particles. Instead of generating divs etc on the fly, you pre-allocate a fixed number of them, and mark them all as "ready for use", then when you need to draw 20 particles, you grab two "ready for use" and have them say "no longer for use", init them to what the particles need, and when they finish, mark the div as "ready for use" again for the next particle that needs to be shown. That way you never hit garbage collection and things stay smooth.

For the lag, I don't think that's something we even want to solve until after mozfest. Right now the approach is easy to explain, complete with "and if you want to do things really well, you can do prediction on the client! it's hard, but worth it" rather than already having that in.

**Comment by flukeout** [comment]
Oh okay, so less to do with the actual `particles = []` array that holds them, but more to do with DOM manipulation. That's a great idea, and something I've batted around in my head to try sometime. Appending a bunch of elements at once is definitely costly, so I'm curious to try this. 

I wonder if having 100 do-nothing divs there the whole time will affect performance at all. Probably way less than making & destroying new ones all the time.

**Comment by flukeout** [comment]
I'm going to close this and re-file an action issue on `particles.js`

**Comment by Pomax** [comment]
you can do particles = [] and then preallocate 100 actual particles, too (secondary improvement) as long as you can set their values to what a new particle needs. That way the particles array doesn't trash the heap either.

**Comment by flukeout** [comment]
Closing as we're addressing particle engine improvements in other issues now. Thanks for getting the feedback @Pomax
