### ISSUE TITLE
Weird foreach behaviour

### ISSUE THREAD

**Issue by flukeout** [flukeout/snek#45]
Hey @pomax check this out, this code is from the part that kills all the snakes after a round is over..

![image](https://cloud.githubusercontent.com/assets/25212/18899989/2c0ef110-84f2-11e6-8b41-61c3c148e2a0.png)

First it iterates over them with a for loop and then a foreach (and consoles each time), now check out the server console for a game with 3 snakes..

![image](https://cloud.githubusercontent.com/assets/25212/18900001/44b3f828-84f2-11e6-9b8a-a45462a39969.png)

Only two snakes in the for each, what's going on here? Is that expected?

**Comment by flukeout** [comment]
Okay i realized why, the .die is splicing it out of the 'snakes' array, so it doesn't fire for all the snakes. We need to defer the actual killing until this loop is over or handle snake death some other way.

**Comment by flukeout** [comment]
Would this work, or would the snakes.length value change as the loop iterated?

```
for(var i = 0; i < this.snakes.length; i++) {
  var snake = this.snakes[0];
  snake.die("quiet",true);
}
```

**Comment by flukeout** [comment]
well, this works... but is lame

```
var num = parseInt(this.snakes.length);

for(var i = 0; i < num; i++) {
  var snake = this.snakes[0];
  snake.die("quiet",true);
}
```

**Comment by flukeout** [comment]
I think this was causing the 'double win'. At the end of the game we try to kill all snakes, but miss some due to this error (and miss them again on resetGame), so we have some snakes lingering that were long enough to win. As soon as the round starts _boom_ we have another winner.

I'm testing now, so hopefully this is the case.

**Comment by Pomax** [comment]
if you need concurrent iteration (e,g, run over array while also splicing), use a reverse loop. forward loops are not concurrent modification safe, reverse  loops are:

```
for(var i=array.length-1; i>=0; i--) {
  var thing = array[i];
  // do whatever you want with thing, or the array,
  // since it won't affect array element i-1, which we
  // iterate to next.
}
```

if you use a forward array, then splicing will cause your `i` to "skip over" elements on the next iteration (or however much you spliced out). That does not happen with reverse runs.

**Comment by flukeout** [comment]
That is much cleaner! I'll update it in the places where it was happening to reverse-o-matic.
It was the main source of our bugs!

**Comment by flukeout** [comment]
Fix'd
