### ISSUE TITLE
Add indicator for local player on client view.

### ISSUE THREAD

**Issue by flukeout** [flukeout/snek#7]
It's hard to tell what snake you are when you are playing with a few players. Let's add an indicator to help the player figure it out when they spawn.

**Comment by Pomax** [comment]
We can add a class to "own snake" and then do some CSS experiments?

**Comment by flukeout** [comment]
Definitely.

**Comment by flukeout** [comment]
We sort of have the player name pop up now, so that should help? Will close until we need it for sure.
