### ISSUE TITLE
When a snake spawns, other snakes shouldn't be able to run into it before it moves.

### ISSUE THREAD

**Issue by flukeout** [flukeout/snek#8]
Currently you can suddently run into a snake that spawned in front of you. We could..
- Wait until that player has moved
- Give them 3 seconds of 'immune' movement before we start tracking collisions

**Comment by Pomax** [comment]
hm, we don't insta-kill snakes though, so we could also treat it as a fact of snek? "the more people play, the more likely killing someone can lead to running into them - stay vigilant!"

**Comment by flukeout** [comment]
yeah - i guess it's just that instance when someone spawns directly in front of you just before you run into them with no warning. You lose a bunch of segments before you can react.

Maybe just like one second of 'non-collision' after spawn with a better visual spawn indicator.

**Comment by Pomax** [comment]
server knows where everyone is, too, we could pick a spawn location that isn't in the direct path of any head segments.

**Comment by flukeout** [comment]
Yeah, that's also an option.

**Comment by Pomax** [comment]
implementing as:
- non-colliding snake if you've not moved
- count for collision if you've moved

**Comment by Pomax** [comment]
implemented by adding a `if (!this.moving && !this.debug) return` during the move call
