### ISSUE TITLE
makeBomb gets fired twice when you drop a bomb and it detonates

### ISSUE THREAD

**Issue by flukeout** [flukeout/snek#9]
STR:
- With just one player, start moving and drop a bomb
- Watch teh console and animatons
- It goes off twice

cc @Pomax related to today's bomb work?

**Comment by Pomax** [comment]
hmmm... didn't really touch anything in the bomb logic, but let's have a look at this tomorrow.

**Comment by flukeout** [comment]
it's actually because removeBomb goes off twice in `client/game.js`

**Comment by Pomax** [comment]
only place that gets triggered is https://github.com/flukeout/snek/blob/gh-pages/client/sockethandling.js#L77 though, as far as I can tell - is the client getting the notice from the server twice?

**Comment by flukeout** [comment]
I'll dig into it more but that is my suspicion

**Comment by Pomax** [comment]
apparently our future snakes got the same eventQ as current snakes, so a current snake with "bomb" instruction would create a future snake for collision detection, which would also have "bomb" as instruction. Which it would drop. And then current snake would drop one too. And now we have future bombs from future snakes blowing up in the past O_O

WE BROKE CAUSALITY!

I fixed it though. Future snakes now start with empty eventQ/directionQ.

**Comment by flukeout** [comment]
You're like the Terminator.
